### ISSUE TITLE
Array parameter is not sent correctly

### ISSUE THREAD

**Issue by IonicaBizau** [jxmono/bind#7]
``` js
"myEvent": [                                      
    {                                           
        "handler": {                            
            "name": "myFoo",    
            "args": [                           
                [                               
                    "someFoo"
                    "anotherFoo"
                ]                               
            ]                                   
        }                                       
    }                                           
]                                               
```

`myFoo` function is called with an object in the following format:

``` js
{
  "1": "someFoo",
  "2": "anotherFoo"
}
```

The first parameter is supposed to be an `Array`, not an `Object`.

**Comment by IonicaBizau** [comment]
Closing as obsolete.

**Comment by gabipetrovay** [comment]
I would leave this open. I can imagine that this will hit us at some point. One that uses array iteration will get an error. What do you think?

**Comment by IonicaBizau** [comment]
> I can imagine that this will hit us at some point. One that uses array iteration will get an error. What do you think?

I don't think so. We will use Engine where this was already fixed. :smile:

**Comment by gabipetrovay** [comment]
So we can close it when all Mono projects that use bind are migrated. :smile:
