### ISSUE TITLE
Do not convert HTML to string

### ISSUE THREAD

**Issue by IonicaBizau** [jxmono/bind#8]
We can remove this: https://github.com/jillix/bind/blob/4794a6fc4c86b1a19a4763feeea2a781ac0eacc2/bind.js#L205-L209

This will allow us to pass jQuery objects instead of simple HTML as string.

**Comment by gabipetrovay** [comment]
Can you please give me a `Bind` use case?

**Comment by IonicaBizau** [comment]
If the template has attached event handlers, then they will be lost when converting the jQuery object to string.
